# Generated by Django 5.2.17 on 2026-09-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
